# ===================================================================
# 基础配置
# ===================================================================
config:
  db:
    host: xxx
    port: 3306
    dbname: xxx
    username: root
    password: xxx
  redis:
    database: 6
    host: xxx
    port: 6379
    password: xxx
  elasticsearch:
    host: xxx
    port: 9200
  mail:
    host: smtp.qq.com
    port: 465
    username: xxx
    password: xxx
  # ===================================================================
  # 前端地址
  # ===================================================================
  vue:
    address: http://localhost:8080/#
# ===================================================================
# Swagger 配置
# ===================================================================
knife4j:
  production: false # true swagger会无法访问
  #  markdowns: classpath:markdown/*
  basic:
    enable: true
    username: admin
    password: 123


# ===================================================================
# 日志配置
# ===================================================================
logging:
  config: classpath:logback-spring.xml
debug: true
# ===================================================================
# 端口路径配置
# ===================================================================
server:
  port: 8880
  servlet:
    context-path: /
# ===================================================================
# Spring 配置
# ===================================================================
spring:
  application:
    name: awesome-blog
  # ===================================================================
  # ElasticSearch 配置
  # ===================================================================
  elasticsearch:
    rest:
      uris:
        - ${config.elasticsearch.host}:${config.elasticsearch.port}
  # ===================================================================
  # MySQL 配置
  # ===================================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${config.db.host}:${config.db.port}/${config.db.dbname}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${config.db.username}
    password: ${config.db.password}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1200000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # ===================================================================
  # Redis 配置
  # ===================================================================
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s
  redis:
    database: ${config.redis.database}
    host: ${config.redis.host}
    password: ${config.redis.password}
    port: ${config.redis.port}

  # ===================================================================
  # Jackson 配置
  # ===================================================================
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

  # ===================================================================
  # 邮件配置
  # ===================================================================
  mail:
    host: ${config.mail.host}
    username: ${config.mail.username}
    password: ${config.mail.password}
    port: ${config.mail.port}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          socketFactory:
            port: ${config.mail.port}
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            trust: ${config.mail.host}

# ===================================================================
# mybatis-plus 配置
# ===================================================================
mybatis-plus:
  type-aliases-package: cn.mirrorming.blog.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 输出SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ===================================================================
# SpringSecurity OAuth2 配置
# ===================================================================
security:
  oauth2:
    clients:
      - client-id: blog
        client-secret: blog
        access-token-seconds: 720000
  social:
    qq:
      app-id: xxx
      app-secret: xxx
      provider-id: qq
    #GitHub配置
    github:
      app-id: xxx
      app-secret: xxx
      provider-id: github
    gitee:
      app-id: xxx
      app-secret: xxx
      provider-id: gitee

common:
  registered-scene:
    login: true
    social: true
    register: false
  sms-scene:
    login: ali