version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog:1.0.0
    container_name: blog
    restart: always
    networks:
      - nets
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx256M -Duser.timezone=GMT+08
networks:
  nets:
    external: false