version: '3.1'
services:
  blog:
    hostname: blog
    image: mireal/blog
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - blog

networks:
  blog:
    external:
      name: blog